name: ecs-web-app-workflow
on: workflow_dispatch
jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
            # Checkout the repo
            - name: Code Checkout
              uses: actions/checkout@v4
            
            # maven and Checkstyletest
            - name: maven test
              run: mvn test
            - name: Checkstyle
              run: mvn checkstyle:checkstyle
            - name: Set up java 11
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin' # See 'Supported distributions' for available options
                java-version: '11'
            # Setup sonar-scanner
            - name: Setup SonarQube
              uses: warchant/setup-sonar-scanner@v7
            # Run sonar-scanner
            - name: SonarQube Scan
              run: sonar-scanner
                -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
                -Dsonar.login=${{ secrets.SONAR_TOKEN }}
                -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
                -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
                -Dsonar.sources=/src
                -Dsonar.junit.reportsPath=target/surefire-reports/ 
                -Dsonar.jacoco.reportsPath=target/jacoco.exec 
                -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
                -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/
              
              